import { readJson, dataPath } from "@/lib/file-io";

interface SlackTemplate {
  template?: string;
}

const DEFAULT_SLACK_TEMPLATE = `Weekly Marketing Report
============================
Blog
  Published: {blog_articles} | Total Views: {blog_views} | Daily +{blog_delta}
  Top: {blog_top}

Google Search Console (7d)
  Clicks: {gsc_clicks} | Impressions: {gsc_impressions} | CTR: {gsc_ctr}%
  Top: {gsc_top_keywords}

Google Analytics (7d)
  Sessions: {ga_sessions} | Pageviews: {ga_pageviews}
============================
Generated by Marketing Hub`;

export async function GET(request: Request) {
  const tmplData = readJson<SlackTemplate>(dataPath("slack-template.json"));
  let template = tmplData?.template || DEFAULT_SLACK_TEMPLATE;

  const origin = new URL(request.url).origin;
  const vars: Record<string, string | number> = {
    dashboard_url: origin,
    blog_articles: 0,
    blog_views: 0,
    blog_delta: 0,
    blog_top: "-",
    gsc_clicks: 0,
    gsc_impressions: 0,
    gsc_ctr: "0",
    gsc_top_keywords: "-",
    ga_sessions: 0,
    ga_pageviews: 0,
  };

  // Try fetching blog stats
  try {
    const blogRes = await fetch(`${origin}/api/blog-stats`, { signal: AbortSignal.timeout(5000) });
    if (blogRes.ok) {
      const blog = await blogRes.json();
      if (!blog.error) {
        vars.blog_articles = blog.totalArticles || 0;
        vars.blog_views = blog.totalViews || 0;
        vars.blog_delta = blog.dailyDelta || 0;
        vars.blog_top = (blog.topArticle?.title || "-").slice(0, 30);
      }
    }
  } catch { /* ignore */ }

  // Replace template variables
  let report = template;
  for (const [key, val] of Object.entries(vars)) {
    report = report.replace(new RegExp(`\\{${key}\\}`, "g"), String(val));
  }

  return Response.json({ report, variables: vars });
}
