import fs from "fs";
import path from "path";
import { readJson, configPath, dataPath } from "@/lib/file-io";

const VIDEO_OUTPUT_DIR = dataPath("videos");

interface OpenClawConfig {
  plugins?: {
    entries?: Record<string, { enabled?: boolean; config?: Record<string, string> }>;
  };
}

export async function POST(request: Request) {
  const data = await request.json();
  const filename: string = data.filename || "";
  const title: string = data.title || "";
  const description: string = data.description || "";
  const tags: string[] = data.tags || [];
  const platform: string = data.platform || "youtube";

  if (!filename) {
    return Response.json({ error: "filename required" }, { status: 400 });
  }

  const videoPath = path.join(VIDEO_OUTPUT_DIR, filename);
  if (!fs.existsSync(videoPath)) {
    return Response.json({ error: "video not found" }, { status: 404 });
  }

  if (platform === "youtube") {
    const config = readJson<OpenClawConfig>(configPath("openclaw.json")) || {};
    const ytCfg = config.plugins?.entries?.["youtube-publish"]?.config || {};
    const accessToken = ytCfg.accessToken || "";
    if (!accessToken) {
      return Response.json(
        { error: "YouTube credentials not configured. Set Access Token in YouTube channel Settings." },
        { status: 400 },
      );
    }

    try {
      const videoSize = fs.statSync(videoPath).size;
      const metadata = JSON.stringify({
        snippet: {
          title: title || filename,
          description: description || "Generated by Marketing Hub",
          tags: tags || [],
          categoryId: "27",
        },
        status: {
          privacyStatus: "public",
          selfDeclaredMadeForKids: false,
          madeForKids: false,
        },
      });

      // Step 1: Init resumable upload
      const initRes = await fetch(
        "https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status",
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": "application/json; charset=UTF-8",
            "X-Upload-Content-Type": "video/mp4",
            "X-Upload-Content-Length": String(videoSize),
          },
          body: metadata,
          signal: AbortSignal.timeout(15000),
        },
      );

      const uploadUrl = initRes.headers.get("Location");
      if (!uploadUrl) {
        return Response.json({ error: "Failed to get upload URL" }, { status: 500 });
      }

      // Step 2: Upload video
      const videoData = fs.readFileSync(videoPath);
      const uploadRes = await fetch(uploadUrl, {
        method: "PUT",
        headers: { "Content-Type": "video/mp4" },
        body: videoData,
        signal: AbortSignal.timeout(120000),
      });
      const result = await uploadRes.json();
      const videoId = result.id || "";

      return Response.json({
        ok: true,
        platform: "youtube",
        videoId,
        url: `https://youtube.com/shorts/${videoId}`,
      });
    } catch (e) {
      return Response.json({ error: String(e) }, { status: 500 });
    }
  }

  if (platform === "tiktok") {
    return Response.json({ error: "TikTok publishing requires app review." });
  }

  return Response.json({ error: `Unknown platform: ${platform}` }, { status: 400 });
}
