import fs from "fs";
import path from "path";
import { dataPath } from "@/lib/file-io";
import { effectiveTenantId } from "@/lib/tenant-auth";
import { runWithTenant } from "@/lib/tenant-context";
import { getChannelCred } from "@/lib/publish";
import { refreshYoutubeAccessToken } from "@/lib/youtube-token";

// finding 6: VIDEO_OUTPUT_DIR을 module scope 상수(`const VIDEO_OUTPUT_DIR = dataPath("videos")`)로
// 두면 import 시점(모듈 최초 로드, 요청/테넌트 컨텍스트 밖)에 단 한 번 dataPath()가 평가된다 —
// 그 시점엔 runWithTenant AsyncLocalStorage 컨텍스트가 없어 tenantSeg()가 항상 ""(공유 루트)로
// 고정되고, 이후 모든 요청(테넌트 무관)이 같은 경로를 공유하게 된다. 파일명은 사용자 입력이라
// 테넌트 간 파일 존재 유무·경로가 새는 구조. 반드시 요청 핸들러 "안", tenantId가 확정된
// runWithTenant(tenantId, ...) 컨텍스트 안에서만 dataPath()를 호출한다.
function resolveVideoPath(filename: string): string {
  return path.join(dataPath("videos"), filename);
}

export async function POST(request: Request) {
  const data = await request.json();
  const filename: string = data.filename || "";
  const title: string = data.title || "";
  const description: string = data.description || "";
  const tags: string[] = data.tags || [];
  const platform: string = data.platform || "youtube";
  const accountId: string | undefined = typeof data.account_id === "string" && data.account_id ? data.account_id : undefined;

  if (!filename) {
    return Response.json({ error: "filename required" }, { status: 400 });
  }
  // path traversal 방지 — 파일명에 구분자/상위경로 금지(테넌트 스코프 디렉터리를 벗어나지 못하게).
  if (filename.includes("/") || filename.includes("\\") || filename.includes("..")) {
    return Response.json({ error: "invalid filename" }, { status: 400 });
  }

  const tenantId = await effectiveTenantId(request, null);

  return runWithTenant(tenantId, async () => {
    const videoPath = resolveVideoPath(filename);
    if (!fs.existsSync(videoPath)) {
      return Response.json({ error: "video not found" }, { status: 404 });
    }

    if (platform === "youtube") {
      // SNS-006 SSOT 통일: /channels/youtube 연결 버튼이 저장하는 DB integrations를 그대로 읽는다
      // (과거엔 openclaw.json 파일을 별도로 읽어 연결해도 "credentials not configured"로 막혔다).
      if (!tenantId) return Response.json({ error: "테넌트를 확인할 수 없습니다." }, { status: 400 });
      const cred = await getChannelCred(tenantId, "youtube", accountId);
      let accessToken = cred?.token || "";
      if (!accessToken) {
        return Response.json(
          { error: "YouTube가 연결되지 않았습니다. /channels/youtube에서 YouTube OAuth 연결을 먼저 완료해주세요." },
          { status: 400 },
        );
      }

      try {
        const videoSize = fs.statSync(videoPath).size;
        const metadata = JSON.stringify({
          snippet: {
            title: title || filename,
            description: description || "Generated by Marketing Hub",
            tags: tags || [],
            categoryId: "27",
          },
          status: {
            privacyStatus: "public",
            selfDeclaredMadeForKids: false,
            madeForKids: false,
          },
        });

        // finding 5: 만료된 access_token으로 최초 시도 → 401이면 공유 헬퍼로 정확히 1회만
        // refresh 후 재시도(무한 재시도 루프 금지). 두 번째 시도도 실패하면 그대로 에러 반환.
        const initUploadOnce = (token: string) =>
          fetch(
            "https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status",
            {
              method: "POST",
              headers: {
                Authorization: `Bearer ${token}`,
                "Content-Type": "application/json; charset=UTF-8",
                "X-Upload-Content-Type": "video/mp4",
                "X-Upload-Content-Length": String(videoSize),
              },
              body: metadata,
              signal: AbortSignal.timeout(15000),
            },
          );

        let initRes = await initUploadOnce(accessToken);
        if (initRes.status === 401) {
          const refreshed = await refreshYoutubeAccessToken(tenantId, accountId);
          if (!refreshed.ok || !refreshed.accessToken) {
            return Response.json(
              { error: refreshed.error || "YouTube 인증이 만료되었습니다. 다시 연결해주세요." },
              { status: 401 },
            );
          }
          accessToken = refreshed.accessToken;
          initRes = await initUploadOnce(accessToken);
        }

        if (!initRes.ok) {
          return Response.json({ error: `YouTube 업로드 초기화 실패 (오류 코드 ${initRes.status}).` }, { status: initRes.status === 401 ? 401 : 502 });
        }

        const uploadUrl = initRes.headers.get("Location");
        if (!uploadUrl) {
          return Response.json({ error: "Failed to get upload URL" }, { status: 500 });
        }

        // Step 2: Upload video
        const videoData = fs.readFileSync(videoPath);
        const uploadRes = await fetch(uploadUrl, {
          method: "PUT",
          headers: { "Content-Type": "video/mp4" },
          body: videoData,
          signal: AbortSignal.timeout(120000),
        });
        const result = await uploadRes.json();
        const videoId = result.id || "";

        return Response.json({
          ok: true,
          platform: "youtube",
          videoId,
          url: `https://youtube.com/shorts/${videoId}`,
        });
      } catch {
        // finding 7: provider raw 에러/스택트레이스를 그대로 노출하지 않는다.
        return Response.json({ error: "YouTube 업로드 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요." }, { status: 500 });
      }
    }

    // SNS-006: TikTok/Reels는 "구현됨"으로 오인되지 않게 정확한 미충족 사유를 준다(추측 금지).
    if (platform === "tiktok") {
      return Response.json(
        { error: "TikTok 발행은 아직 구현되지 않았습니다 — TikTok 앱 심사(Content Posting API) 승인 전이라 credential 자체가 없습니다.", disabled: true, reason: "not_implemented" },
        { status: 501 },
      );
    }
    if (platform === "reels" || platform === "instagram_reels") {
      return Response.json(
        { error: "Instagram Reels 발행 분기는 아직 구현되지 않았습니다.", disabled: true, reason: "not_implemented" },
        { status: 501 },
      );
    }

    return Response.json({ error: `Unknown platform: ${platform}` }, { status: 400 });
  });
}
