import { readJson, writeJson, dataPath } from "@/lib/file-io";

interface SlackTemplate {
  template?: string;
}

const DEFAULT_SLACK_TEMPLATE = `Weekly Marketing Report
============================
Blog
  Published: {blog_articles} | Total Views: {blog_views} | Daily +{blog_delta}
  Top: {blog_top}

Google Search Console (7d)
  Clicks: {gsc_clicks} | Impressions: {gsc_impressions} | CTR: {gsc_ctr}%
  Top: {gsc_top_keywords}

Google Analytics (7d)
  Sessions: {ga_sessions} | Pageviews: {ga_pageviews}
============================
Generated by Marketing Hub`;

export { DEFAULT_SLACK_TEMPLATE };

export async function GET() {
  const tmpl = readJson<SlackTemplate>(dataPath("slack-template.json"));
  return Response.json({
    template: tmpl?.template || DEFAULT_SLACK_TEMPLATE,
  });
}

export async function POST(request: Request) {
  const data = await request.json();
  writeJson(dataPath("slack-template.json"), {
    template: data.template || DEFAULT_SLACK_TEMPLATE,
  });
  return Response.json({ ok: true });
}
